Added new task to get Service Bus Queue information from desired queues.
FrendsPlatform/Frends.AzureServiceBus pull request #2
Opened 2021-10-07 11:29 UTC by Svenskapojkarna

2021-10-14 09:20 UTC, EkiH requested changes

2021-10-14 09:20 UTC, EkiH commented on Frends.AzureServiceBus/Definitions.cs
> +        public List<QueueRuntimeInfo> QueueInfos { get; set; }
We should probably map the QueueRuntimeInfo to our own class since the Process using the Task will not have a reference to the Service Bus library.

2021-10-14 09:20 UTC, EkiH commented on Frends.AzureServiceBus/Frends.AzureServiceBus.csproj
> +    <Description>New task added to get message count and information from desired Service Bus queues.</Description>
This is the description, don't put version history here

2021-10-14 11:36 UTC, EkiH approved these changes

2021-10-15 07:21 UTC, OssiGalkin commented
- Remove unnecessary cancellation token
- Add documentation to README.md
- Add link to documentation in xml documentation

Otherwise seems good 👍

2021-10-15 08:27 UTC, merged